import os

from huggingface_hub import list_repo_files

MODEL_CONFIGS = {
    "lwdetr_large_60e_coco": {
        "batch_size": 2,
        "encoder": "vit_small",
        "vit_encoder_num_layers": 10,
        "window_block_indexes": [0, 1, 3, 6, 7, 9],
        "out_feature_indexes": [2, 4, 5, 9],
        "dec_layers": 3,
        "group_detr": 13,
        "two_stage": True,
        "projector_scale": ["P3", "P5"],
        "hidden_dim": 384,
        "sa_nheads": 12,
        "ca_nheads": 24,
        "dec_n_points": 4,
        "bbox_reparam": True,
        "lite_refpoint_refine": True,
        "num_select": 300,
        "dataset_file": "coco",
        "square_resize_div_64": True,
        "use_ema": True,
        "eval": True,
        "num_queries": 300,
    },
    "lwdetr_small_60e_coco": {
        "encoder": "vit_tiny",
        "vit_encoder_num_layers": 10,
        "window_block_indexes": [0, 1, 3, 6, 7, 9],
        "out_feature_indexes": [2, 4, 5, 9],
        "dec_layers": 3,
        "group_detr": 13,
        "two_stage": True,
        "projector_scale": ["P4"],
        "hidden_dim": 256,
        "sa_nheads": 8,
        "ca_nheads": 16,
        "dec_n_points": 2,
        "bbox_reparam": True,
        "lite_refpoint_refine": True,
        "num_select": 300,
        "confidence_threshold": 0.5,
        "num_queries": 300,
    },
    "lwdetr_xlarge_60e_coco": {
        "batch_size": 1,
        "encoder": "vit_base",
        "vit_encoder_num_layers": 10,
        "window_block_indexes": [0, 1, 3, 6, 7, 9],
        "out_feature_indexes": [2, 4, 5, 9],
        "dec_layers": 3,
        "group_detr": 13,
        "two_stage": True,
        "projector_scale": ["P3", "P5"],
        "hidden_dim": 384,
        "sa_nheads": 12,
        "ca_nheads": 24,
        "dec_n_points": 4,
        "bbox_reparam": True,
        "lite_refpoint_refine": True,
        "num_select": 300,
        "square_resize_div_64": True,
        "use_ema": True,
        "eval": True,
        "num_queries": 300,
    },
    "lwdetr_medium_60e_coco": {
        "batch_size": 1,
        "encoder": "vit_small",
        "vit_encoder_num_layers": 10,
        "window_block_indexes": [0, 1, 3, 6, 7, 9],
        "out_feature_indexes": [2, 4, 5, 9],
        "dec_layers": 3,
        "group_detr": 13,
        "two_stage": True,
        "projector_scale": ["P4"],
        "hidden_dim": 256,
        "sa_nheads": 8,
        "ca_nheads": 16,
        "dec_n_points": 2,
        "bbox_reparam": True,
        "lite_refpoint_refine": True,
        "num_select": 300,
        "square_resize_div_64": True,
        "use_ema": True,
        "eval": True,
        "num_queries": 300,
    },
    "lwdetr_tiny_60e_coco": {
        "batch_size": 1,
        "encoder": "vit_tiny",
        "vit_encoder_num_layers": 6,
        "window_block_indexes": [0, 2, 4],
        "out_feature_indexes": [1, 3, 5],
        "dec_layers": 3,
        "group_detr": 13,
        "two_stage": True,
        "projector_scale": ["P4"],
        "hidden_dim": 256,
        "sa_nheads": 8,
        "ca_nheads": 16,
        "dec_n_points": 2,
        "bbox_reparam": True,
        "lite_refpoint_refine": True,
        "num_queries": 100,
        "num_select": 100,
        "dataset_file": "coco",
        "square_resize_div_64": True,
        "use_ema": True,
        "eval": True,
    },
}
default_model_parameters = {
    "dataset_file": "coco",
    "device": "cuda",
    "lr": 1e-4,
    "lr_encoder": 1.5e-4,
    "weight_decay": 1e-4,
    "epochs": 12,
    "lr_drop": 11,
    "clip_max_norm": 0.1,
    "lr_vit_layer_decay": 0.8,
    "lr_component_decay": 1.0,
    "dropout": 0,
    "drop_path": 0,
    "drop_mode": "standard",
    "drop_schedule": "constant",
    "cutoff_epoch": 0,
    "position_embedding": "sine",
    "dim_feedforward": 2048,
    "decoder_norm": "LN",
    "set_cost_class": 2.0,
    "set_cost_bbox": 5.0,
    "set_cost_giou": 2.0,
    "cls_loss_coef": 2.0,
    "bbox_loss_coef": 5.0,
    "giou_loss_coef": 2.0,
    "focal_alpha": 0.25,
    "aux_loss": True,
    "sum_group_losses": False,
    "use_varifocal_loss": False,
    "use_position_supervised_loss": False,
    "ia_bce_loss": False,
    "pretrained_encoder": None,
    "pretrain_weights": None,
    "pretrain_exclude_keys": None,
    "pretrain_keys_modify_to_load": None,
    "output_dir": "output",
    "checkpoint_interval": 10,
    "seed": 42,
    "resume": "",
    "start_epoch": 0,
    "ema_decay": 0.9997,
    "num_workers": 2,
    "world_size": 1,
    "dist_url": "env://",
    "sync_bn": True,
    "fp16_eval": False,
}


SUBDIR = "pretrain_weights"
COCO_CLASSES = [
    "__background__",
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "N/A",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "N/A",
    "backpack",
    "umbrella",
    "N/A",
    "N/A",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "N/A",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "N/A",
    "dining table",
    "N/A",
    "N/A",
    "toilet",
    "N/A",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "N/A",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
]

REPO_ID = "xbsu/LW-DETR"

all_files = list_repo_files(REPO_ID)
weight_files = [f for f in all_files if f.startswith(SUBDIR) and f.endswith(".pth")]

MODEL_DICT = {}

for file_path in weight_files:
    model_name = os.path.splitext(os.path.basename(file_path))[
        0
    ]  # e.g., "LWDETR_tiny_60e_coco"
    MODEL_DICT[model_name] = file_path
